### PR TITLE
update docs to reflect branding change to uHenry

### PR DESCRIPTION
**Pull request by plushugh**

### CODE REVIEW

**Review by Treeezheng — COMMENTED** [review]
Great

**Comment by Treeezheng** [comment]
Good

**Review by Treeezheng — COMMENTED** [review]
Thank u Hugh He

**Review by Arom1a — COMMENTED** [review]
Goooood

**Review by Arom1a — APPROVED** [review]

**Comment by plushugh** [comment]
Merged. 🧑‍🚀👨‍🚀👩‍🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

**Pull request merged**
